<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcgvgTl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcgvgTl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcgvgTl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcgvgTl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcgvgTl\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcgvgTl',
    'container.build_id' => '6ff5ab69',
    'container.build_time' => 1620927986,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcgvgTl');
