<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnwFkp6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnwFkp6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnwFkp6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnwFkp6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVnwFkp6\App_KernelDevDebugContainer([
    'container.build_hash' => 'VnwFkp6',
    'container.build_id' => '11c24c2f',
    'container.build_time' => 1620887485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnwFkp6');
